### ISSUE TITLE
Should use global leaflet L object if it exists

### ISSUE THREAD

**Issue by batpad** [perliedman/lrm-mapbox#2]
This line: `L.Routing = L.Routing || {};` lands up clobbering an already defined L.Routing object if the project includes Leaflet via a `<script>` tag and not browserify.

Will make a pull request with a fix, let me know if you need some example scenarios where this would be useful - I ran into this when trying to add lrm-mapbox as a router to the [osrm-frontend-v2](https://github.com/Project-OSRM/osrm-frontend-v2/) code.

**Comment by perliedman** [comment]
Mixing multiple instances of Leaflet and has always lead to headaches and tears when I've done it (accidentally or on purpose).

I'm not sure we can work around this in a sane way, but feel free to prove me wrong :smile:. I'd either use the packaged dist files without Browserify or similar, loading Leaflet from a `<script>`, or use Browserify all the way.

**Comment by batpad** [comment]
You are correct. I just broke my brains trying to implement that and it's not pretty or fun. Not a problem with lrm-mapbox. Closing :). (thanks so much for the quick response!)
